### ISSUE TITLE
Not working in fragments

### ISSUE THREAD

**Issue by smarakjeet301** [akshay2211/PixImagePicker#105]
How to get it working on fragments

**Comment by akshay2211** [comment]
Hello @smarakjeet301 
Thanks for Trying out [PixImagePicker](https://github.com/akshay2211/PixImagePicker) 
You can use [PixImagePicker](https://github.com/akshay2211/PixImagePicker) in fragments just like you use in an Activity , you just have to pass the fragment instance in pix constructor instead of Activity instance.
For more detail refer to [SampleFragment.java](https://github.com/akshay2211/PixImagePicker/blob/master/app/src/main/java/com/fxn/pixsample/SampleFragment.java ) created in project.

**Comment by TinaT2** [comment]
It is not working to call pix from fragments.
Also, the sample link posted is 404.

**Comment by akshay2211** [comment]
@TinaT2 Thanks for pointing out the issue, I've updated the link, also you can refer to these [Helper methods](https://github.com/akshay2211/PixImagePicker/blob/master/pix/src/main/java/io/ak1/pix/helpers/UsabilityHelper.kt)
to create and utilize Pix Fragment

**Comment by AtineKeshishi** [comment]
The FragmentSample.java you mentioned is an activity that calls addPixToActivity() to display the PixFragment. 
pixFragmen() does not display the PixFragment in fragments.
