### ISSUE TITLE
onActivityResult and onRequestPermissionsResult deprecations

### ISSUE THREAD

**Issue by joey-harward** [akshay2211/PixImagePicker#176]
Will you handle the deprecation of onActivityResult and onRequestPermissionsResult?

**Comment by aliraza12636** [comment]
If you are not receiving calls for onActivityResult, I was also facing this problem. what I was doing is, calling Pix.start.. from a fragment and so I was not getting a callback of onActivityResult, the fix is, handle the callback inside the parent activity of the fragment and then call the fragment's onActivityResult manually with the recived parametes.

       e.g.
  

override in the parent activity


      @Override
    protected void onActivityResult(int requestCode, int resultCode, @Nullable Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        mainChatFragment.onActivityResult(requestCode, resultCode, data);
    }


that worked for me.

**Comment by akshay2211** [comment]
for the latest version [1.6.2](https://github.com/akshay2211/PixImagePicker#download)
onActivityResult is not needed
