### ISSUE TITLE
Updated version not working

### ISSUE THREAD

**Issue by vivekpchrome** [akshay2211/PixImagePicker#71]
Hi Team ,

After the code update 1.3.0 the Pix.start method not working as expected it is showing that Cannot find method start . Activity extends AppCompatActivity  and it is asking for FragmentActivity .

**Comment by devLaaziz** [comment]
+

**Comment by agonshehu** [comment]
I have the same issue. Thanks.

**Comment by akshay2211** [comment]
Hello @vivekpchrome 

This is because [Pix](https://github.com/akshay2211/PixImagePicker) is using the new Material library with the legacy Support Library. You have to migrate to android.support to androidx in order to use com.google.android.material. 

With Android Studio 3.2 and higher, you can quickly migrate an existing project to use AndroidX by selecting Refactor > Migrate to AndroidX from the menu bar.

For more details kindly refer [Migrating to AndroidX](https://developer.android.com/jetpack/androidx/migrate#migrate)

**Comment by agonshehu** [comment]
I figured it out quickly after i wrote it as an issue. I found something
that when i take a picture and upload it to firebase the image is correctly
oriented, but if i take a pic with my phones camera in portrait mode and
then afterwards upload it to firebase via your librarys gallery, the image
is rotated -90 degrees. Can you check what that is?

Thanks and great library by the way.
